create table support_chat_messages (
    id bigint generated by default as identity,
    client_company_id bigint not null,
    author_name varchar(255) not null,
    author_role varchar(255) not null,
    message varchar(4000) not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint fk_support_chat_messages_client_company
        foreign key (client_company_id) references client_companies (id)
);

create index idx_support_chat_messages_company_created_at
    on support_chat_messages (client_company_id, created_at);
