export const mockData = {
  roles: [
    { value: 'ADMIN', label: 'Администратор' },
    { value: 'MANAGER', label: 'Менеджер' },
    { value: 'EXECUTOR', label: 'Исполнитель' },
    { value: 'CLIENT', label: 'Клиент' },
  ],
  statuses: [
    { value: 'NEW', label: 'Новый заказ' },
    { value: 'CLARIFICATION', label: 'На уточнении ТЗ' },
    { value: 'DESIGN', label: 'В проектировании' },
    { value: 'WAITING_MATERIALS', label: 'Ожидает материалов' },
    { value: 'CUTTING', label: 'В резке' },
    { value: 'MACHINING', label: 'В мехобработке' },
    { value: 'WELDING', label: 'В сварке' },
    { value: 'HEAT_TREATMENT', label: 'В термообработке' },
    { value: 'COATING', label: 'В покрытии' },
    { value: 'ASSEMBLY', label: 'В сборке' },
    { value: 'READY_FOR_CHECK', label: 'Готов к проверке' },
    { value: 'IN_REVIEW', label: 'На проверке' },
    { value: 'READY_FOR_SHIPMENT', label: 'Готов к отгрузке' },
    { value: 'SHIPPED', label: 'Отгружен' },
    { value: 'CLOSED', label: 'Закрыт' },
    { value: 'ON_HOLD', label: 'Приостановлен' },
    { value: 'CANCELLED', label: 'Отменён' },
  ],
  priorities: [
    { value: 'LOW', label: 'Низкий' },
    { value: 'NORMAL', label: 'Обычный' },
    { value: 'HIGH', label: 'Высокий' },
    { value: 'URGENT', label: 'Срочный' },
  ],
  users: [
    {
      id: 1,
      login: 'admin',
      fullName: 'Администратор Системы',
      email: 'admin@impuls.ru',
      phone: '+7 (900) 000-00-01',
      role: 'ADMIN',
      roleLabel: 'Администратор',
      active: true,
      clientCompanyId: null,
      clientCompanyName: null,
    },
    {
      id: 2,
      login: 'manager',
      fullName: 'Смирнов Алексей',
      email: 'manager@impuls.ru',
      phone: '+7 (900) 000-00-02',
      role: 'MANAGER',
      roleLabel: 'Менеджер',
      active: true,
      clientCompanyId: null,
      clientCompanyName: null,
    },
    {
      id: 3,
      login: 'executor',
      fullName: 'Орлов Дмитрий',
      email: 'executor@impuls.ru',
      phone: '+7 (900) 000-00-03',
      role: 'EXECUTOR',
      roleLabel: 'Исполнитель',
      active: true,
      clientCompanyId: null,
      clientCompanyName: null,
    },
    {
      id: 4,
      login: 'client',
      fullName: 'Клиентский Кабинет',
      email: 'client@metallinvest.ru',
      phone: '+7 (900) 000-00-04',
      role: 'CLIENT',
      roleLabel: 'Клиент',
      active: true,
      clientCompanyId: 1,
      clientCompanyName: 'ООО "МеталлИнвест"',
    },
  ],
  clients: [
    {
      id: 1,
      name: 'ООО "МеталлИнвест"',
      inn: '6601001001',
      contactPerson: 'Иванов Петр Сергеевич',
      phone: '+7 (900) 111-22-33',
      email: 'zakaz@metallinvest.ru',
      city: 'Екатеринбург',
      orderCount: 2,
    },
    {
      id: 2,
      name: 'ООО "УралЭнергоПром"',
      inn: '6601002002',
      contactPerson: 'Кузнецова Мария Андреевна',
      phone: '+7 (900) 222-33-44',
      email: 'orders@uralenergoprom.ru',
      city: 'Нижний Тагил',
      orderCount: 1,
    },
  ],
  orders: [
    {
      id: 1,
      orderNumber: 'IMP-2026-001',
      title: 'Рама агрегата для насосной станции',
      status: 'IN_REVIEW',
      statusLabel: 'На проверке',
      priority: 'HIGH',
      priorityLabel: 'Высокий',
      clientName: 'ООО "МеталлИнвест"',
      managerName: 'Смирнов Алексей',
      executorName: 'Орлов Дмитрий',
      createdAt: '2026-04-27',
      plannedDate: '2026-05-05',
      dueDate: '2026-05-06',
      overdue: true,
    },
    {
      id: 2,
      orderNumber: 'IMP-2026-002',
      title: 'Узел крепления для конвейерной линии',
      status: 'WAITING_MATERIALS',
      statusLabel: 'Ожидает материалов',
      priority: 'NORMAL',
      priorityLabel: 'Обычный',
      clientName: 'ООО "УралЭнергоПром"',
      managerName: 'Смирнов Алексей',
      executorName: 'Орлов Дмитрий',
      createdAt: '2026-05-01',
      plannedDate: '2026-05-09',
      dueDate: '2026-05-14',
      overdue: false,
    },
    {
      id: 3,
      orderNumber: 'IMP-2026-003',
      title: 'Металлоконструкция для корпуса оборудования',
      status: 'READY_FOR_SHIPMENT',
      statusLabel: 'Готов к отгрузке',
      priority: 'URGENT',
      priorityLabel: 'Срочный',
      clientName: 'ООО "МеталлИнвест"',
      managerName: 'Смирнов Алексей',
      executorName: 'Орлов Дмитрий',
      createdAt: '2026-04-18',
      plannedDate: '2026-05-03',
      dueDate: '2026-05-04',
      overdue: false,
    },
  ],
  details: {
    1: {
      id: 1,
      orderNumber: 'IMP-2026-001',
      title: 'Рама агрегата для насосной станции',
      description: 'Изготовление и сборка рамы по КД заказчика, с мехобработкой и окраской.',
      status: 'IN_REVIEW',
      statusLabel: 'На проверке',
      priority: 'HIGH',
      priorityLabel: 'Высокий',
      createdAt: '2026-04-27',
      plannedDate: '2026-05-05',
      dueDate: '2026-05-06',
      completedAt: null,
      overdue: true,
      clientCompany: {
        id: 1,
        name: 'ООО "МеталлИнвест"',
        inn: '6601001001',
        contactPerson: 'Иванов Петр Сергеевич',
        phone: '+7 (900) 111-22-33',
        email: 'zakaz@metallinvest.ru',
        city: 'Екатеринбург',
        orderCount: 2,
      },
      manager: {
        id: 2,
        login: 'manager',
        fullName: 'Смирнов Алексей',
        email: 'manager@impuls.ru',
        phone: '+7 (900) 000-00-02',
        role: 'MANAGER',
        roleLabel: 'Менеджер',
        active: true,
        clientCompanyId: null,
        clientCompanyName: null,
      },
      executor: {
        id: 3,
        login: 'executor',
        fullName: 'Орлов Дмитрий',
        email: 'executor@impuls.ru',
        phone: '+7 (900) 000-00-03',
        role: 'EXECUTOR',
        roleLabel: 'Исполнитель',
        active: true,
        clientCompanyId: null,
        clientCompanyName: null,
      },
      comments: [
        {
          id: 1,
          authorName: 'Менеджер',
          authorRole: 'MANAGER',
          message: 'ТЗ согласовываем с клиентом. Нужна корректировка размеров.',
          visibleToClient: true,
          createdAt: '2026-05-05T12:30:00',
        },
        {
          id: 2,
          authorName: 'ОТК',
          authorRole: 'EXECUTOR',
          message: 'Замечания сняты, можно повторно передавать на проверку.',
          visibleToClient: true,
          createdAt: '2026-05-06T08:10:00',
        },
      ],
      history: [
        {
          id: 1,
          status: 'NEW',
          statusLabel: 'Новый заказ',
          comment: 'Создан заказ и передан в проверку ТЗ',
          changedByName: 'Смирнов Алексей',
          changedByRole: 'MANAGER',
          changedAt: '2026-05-05T06:00:00',
        },
        {
          id: 2,
          status: 'CLARIFICATION',
          statusLabel: 'На уточнении ТЗ',
          comment: 'Получены замечания по чертежам',
          changedByName: 'Смирнов Алексей',
          changedByRole: 'MANAGER',
          changedAt: '2026-05-06T09:15:00',
        },
        {
          id: 3,
          status: 'IN_REVIEW',
          statusLabel: 'На проверке',
          comment: 'Заказ передан на проверку качества',
          changedByName: 'Орлов Дмитрий',
          changedByRole: 'EXECUTOR',
          changedAt: '2026-05-06T12:00:00',
        },
      ],
    },
    2: {
      id: 2,
      orderNumber: 'IMP-2026-002',
      title: 'Узел крепления для конвейерной линии',
      description: 'Партия узлов крепления с резкой, сваркой и контролем ОТК.',
      status: 'WAITING_MATERIALS',
      statusLabel: 'Ожидает материалов',
      priority: 'NORMAL',
      priorityLabel: 'Обычный',
      createdAt: '2026-05-01',
      plannedDate: '2026-05-09',
      dueDate: '2026-05-14',
      completedAt: null,
      overdue: false,
      clientCompany: {
        id: 2,
        name: 'ООО "УралЭнергоПром"',
        inn: '6601002002',
        contactPerson: 'Кузнецова Мария Андреевна',
        phone: '+7 (900) 222-33-44',
        email: 'orders@uralenergoprom.ru',
        city: 'Нижний Тагил',
        orderCount: 1,
      },
      manager: {
        id: 2,
        login: 'manager',
        fullName: 'Смирнов Алексей',
        email: 'manager@impuls.ru',
        phone: '+7 (900) 000-00-02',
        role: 'MANAGER',
        roleLabel: 'Менеджер',
        active: true,
        clientCompanyId: null,
        clientCompanyName: null,
      },
      executor: {
        id: 3,
        login: 'executor',
        fullName: 'Орлов Дмитрий',
        email: 'executor@impuls.ru',
        phone: '+7 (900) 000-00-03',
        role: 'EXECUTOR',
        roleLabel: 'Исполнитель',
        active: true,
        clientCompanyId: null,
        clientCompanyName: null,
      },
      comments: [
        {
          id: 4,
          authorName: 'Мастер участка',
          authorRole: 'EXECUTOR',
          message: 'Часть материалов еще в пути. Ждем поставку.',
          visibleToClient: false,
          createdAt: '2026-05-06T11:20:00',
        },
      ],
      history: [
        {
          id: 4,
          status: 'DESIGN',
          statusLabel: 'В проектировании',
          comment: 'Согласованы основные параметры',
          changedByName: 'Смирнов Алексей',
          changedByRole: 'MANAGER',
          changedAt: '2026-05-03T10:20:00',
        },
        {
          id: 5,
          status: 'WAITING_MATERIALS',
          statusLabel: 'Ожидает материалов',
          comment: 'Ожидаем поставку заготовок',
          changedByName: 'Орлов Дмитрий',
          changedByRole: 'EXECUTOR',
          changedAt: '2026-05-06T12:00:00',
        },
      ],
    },
    3: {
      id: 3,
      orderNumber: 'IMP-2026-003',
      title: 'Металлоконструкция для корпуса оборудования',
      description: 'Заказ на корпусную металлоконструкцию с термообработкой.',
      status: 'READY_FOR_SHIPMENT',
      statusLabel: 'Готов к отгрузке',
      priority: 'URGENT',
      priorityLabel: 'Срочный',
      createdAt: '2026-04-18',
      plannedDate: '2026-05-03',
      dueDate: '2026-05-04',
      completedAt: '2026-05-06',
      overdue: false,
      clientCompany: {
        id: 1,
        name: 'ООО "МеталлИнвест"',
        inn: '6601001001',
        contactPerson: 'Иванов Петр Сергеевич',
        phone: '+7 (900) 111-22-33',
        email: 'zakaz@metallinvest.ru',
        city: 'Екатеринбург',
        orderCount: 2,
      },
      manager: {
        id: 2,
        login: 'manager',
        fullName: 'Смирнов Алексей',
        email: 'manager@impuls.ru',
        phone: '+7 (900) 000-00-02',
        role: 'MANAGER',
        roleLabel: 'Менеджер',
        active: true,
        clientCompanyId: null,
        clientCompanyName: null,
      },
      executor: {
        id: 3,
        login: 'executor',
        fullName: 'Орлов Дмитрий',
        email: 'executor@impuls.ru',
        phone: '+7 (900) 000-00-03',
        role: 'EXECUTOR',
        roleLabel: 'Исполнитель',
        active: true,
        clientCompanyId: null,
        clientCompanyName: null,
      },
      comments: [
        {
          id: 5,
          authorName: 'Менеджер',
          authorRole: 'MANAGER',
          message: 'Заказ готов к отгрузке, согласуем транспорт.',
          visibleToClient: true,
          createdAt: '2026-05-06T09:00:00',
        },
      ],
      history: [
        {
          id: 6,
          status: 'READY_FOR_SHIPMENT',
          statusLabel: 'Готов к отгрузке',
          comment: 'Изготовление завершено',
          changedByName: 'Орлов Дмитрий',
          changedByRole: 'EXECUTOR',
          changedAt: '2026-05-06T10:00:00',
        },
      ],
    },
  },
};
